// <auto-generated />
using System;
using Julio_AP1_P2.Server.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Julio_AP1_P2.Server.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231031182505_Inicial Migration")]
    partial class InicialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Julio_AP1_P2.Shared.Models.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CantidadProducida")
                        .HasColumnType("REAL");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("PesoTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Julio_AP1_P2.Shared.Models.EntradasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CantidadUtilizada")
                        .HasColumnType("REAL");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Julio_AP1_P2.Shared.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripción")
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripción = "Maní",
                            Existencia = 40,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripción = "Pistachos",
                            Existencia = 600,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripción = "Pasas",
                            Existencia = 500,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 4,
                            Descripción = "Ciruelas",
                            Existencia = 700,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 5,
                            Descripción = "Mixto MPP 0.5lb",
                            Existencia = 0,
                            Tipo = 1
                        },
                        new
                        {
                            ProductoId = 6,
                            Descripción = "Mixto MPC 0.5lb",
                            Existencia = 0,
                            Tipo = 1
                        },
                        new
                        {
                            ProductoId = 7,
                            Descripción = "Mixto MPP 0.2lb",
                            Existencia = 0,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("Julio_AP1_P2.Shared.Models.EntradasDetalle", b =>
                {
                    b.HasOne("Julio_AP1_P2.Shared.Models.Entradas", null)
                        .WithMany("EntradasDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Julio_AP1_P2.Shared.Models.Entradas", b =>
                {
                    b.Navigation("EntradasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
